services:
  lambda_ts_template:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lambda_ts_template
    hostname: lambda_ts_template
    shm_size: '4gb'
    volumes:
      - ./:/workspace:cached
      - node_modules:/workspace/node_modules
    environment:
      GIT_AUTHOR_NAME: ${GIT_USERNAME}
      GIT_COMMITTER_NAME: ${GIT_USERNAME}
      GIT_AUTHOR_EMAIL: ${GIT_EMAIL_ADDRESS}
      GIT_COMMITTER_EMAIL: ${GIT_EMAIL_ADDRESS}
      TZ: Asia/Tokyo
    tty: true

volumes:
  node_modules:
